server:
  port: 80

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: alarm-distribution-service
          uri: lb://alarm-distribution-service
          predicates:
            - Path=/alarm-distribution-service/**
          filters:
            - StripPrefix=1
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/slack-service/**
            - Method=GET,POST
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

