server:
  port: 80

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: alarm-distribution-service
          uri: lb://alarm-distribution-service
          predicates:
            - Path=/alarm-distribution-service/v2/api-docs
          filters:
            - StripPrefix=1

        - id: alarm-distribution-service
          uri: lb://alarm-distribution-service
          predicates:
            - Path=/alarm-distribution-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter

        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/slack-service/**
            - Method=GET,POST
          filters:
            - StripPrefix=1

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**

        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/log-service/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/signup,/user-service/signin,/user-service/v2/api-docs

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter