server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: alarm-distribution-service
          uri: lb://ALARM-DISTRIBUTION-SERVICE
          predicates:
            - Path=/alarm-distribution-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/alarm-distribution-service/(?<segment>.*), /$\{segment}
