server:
  port: 80

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: alarm-distribution-service
          uri: lb://ALARM-DISTRIBUTION-SERVICE
          predicates:
            - Path=/alarm-distribution-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/alarm-distribution-service/(?<segment>.*), /$\{segment}
